# Please set 'QIITA_TOKEN' secret to your repository
name: Publish articles

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  publish_articles:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: "18.16.0"
      - name: Install qiita-cli
        run: npm install -g @qiita/qiita-cli@v0.7.0
        shell: bash
      - name: Pull articles
        run: qiita pull
        env:
          QIITA_TOKEN: ${{ secrets.QIITA_TOKEN }}
        shell: bash
      - uses: increments/qiita-cli/actions/publish@v0
        with:
          qiita-token: ${{ secrets.QIITA_TOKEN }}
