# Please set 'QIITA_TOKEN' secret to your repository
name: Pull articles

on:
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  pull_articles:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: "18.16.0"
      - name: Install qiita-cli
        run: npm install -g @qiita/qiita-cli@v1.3.0
        shell: bash
      - name: Pull articles
        run: qiita pull --force
        env:
          QIITA_TOKEN: ${{ secrets.QIITA_TOKEN }}
        shell: bash
      - name: Commit and push diff # Not executed recursively even if `push` is triggered. See https://docs.github.com/en/actions/using-workflows/triggering-a-workflow#triggering-a-workflow-from-a-workflow
        run: |
          git add public/*
          if ! git diff --staged --exit-code --quiet; then
            git config --global user.name 'TORIFUKUKaiou'
            git config --global user.email 'torifuku.kaiou@gmail.com'
            git commit -m '闘魂注入'
            git push
          fi
        shell: bash
